#!/usr/bin/env bash
# ================================================================
# plugin-manager.sh — Dev Container Plugin Manager
#
# Called via the plugin() shell function in .bashrc_devcontainer:
#   plugin() { bash /workspace/.devcontainer/scripts/plugin-manager.sh "$@"; ... }
#
# Never sourced — always run as a subprocess.
# ================================================================
set -euo pipefail

readonly PLUGINS_DIR="/workspace/.plugins"
readonly REGISTRY_FILE="${PLUGINS_DIR}/.registry.json"
readonly LOADER_FILE="${PLUGINS_DIR}/.loader.sh"
readonly MANAGER_VERSION="1"

# ================================================================
# Output helpers
# ================================================================
die()  { echo "  [plugin] ERROR: $*" >&2; exit 1; }
warn() { echo "  [plugin] WARNING: $*" >&2; }
info() { echo "  [plugin] $*"; }

# ================================================================
# bat/batcat/cat fallback for syntax-highlighted display
# ================================================================
_bat() {
  if command -v bat >/dev/null 2>&1; then
    bat "$@"
  elif command -v batcat >/dev/null 2>&1; then
    batcat "$@"
  else
    # Strip bat-specific flags and fall back to cat/less
    local args=()
    for arg in "$@"; do
      case "$arg" in
        --style=*|--paging=*|--language=*) ;;
        --paging) shift ;;
        *) args+=("$arg") ;;
      esac
    done
    cat "${args[@]}"
  fi
}

# ================================================================
# Guard: plugins directory must exist
# ================================================================
require_plugins_dir() {
  if [[ ! -d "$PLUGINS_DIR" ]]; then
    die "Plugin directory ${PLUGINS_DIR} does not exist. Run the devcontainer post-create script first."
  fi
  if [[ ! -f "$REGISTRY_FILE" ]]; then
    echo '{"plugins":{}}' > "$REGISTRY_FILE"
  fi
}

# ================================================================
# Guard: registry must be valid JSON
# ================================================================
ensure_registry_valid() {
  if ! jq empty "$REGISTRY_FILE" 2>/dev/null; then
    warn "Registry file is not valid JSON — resetting to empty registry."
    echo '{"plugins":{}}' > "$REGISTRY_FILE"
  fi
}

# ================================================================
# Validate plugin manifest has required fields
# ================================================================
validate_manifest() {
  local manifest_file="$1"
  if [[ ! -f "$manifest_file" ]]; then
    die "No plugin.json found in $(dirname "$manifest_file")"
  fi
  if ! jq empty "$manifest_file" 2>/dev/null; then
    die "plugin.json is not valid JSON in $(dirname "$manifest_file")"
  fi
  local required_fields=("name" "version" "description")
  for field in "${required_fields[@]}"; do
    local val
    val=$(jq -r ".${field} // empty" "$manifest_file")
    if [[ -z "$val" ]]; then
      die "plugin.json missing required field: ${field}"
    fi
  done
}

# ================================================================
# Reject plugin names with unsafe characters
# ================================================================
sanitize_plugin_name() {
  local name="$1"
  if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    die "Plugin name '${name}' contains invalid characters. Only alphanumeric, hyphens, and underscores are allowed."
  fi
  echo "$name"
}

# ================================================================
# Regenerate .loader.sh from the registry
# ================================================================
generate_loader() {
  require_plugins_dir
  ensure_registry_valid

  local tmp_loader
  tmp_loader="$(mktemp "${PLUGINS_DIR}/.loader_tmp_XXXXXX")"

  {
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by plugin manager — do not edit manually"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    local plugin_names
    plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

    for name in $plugin_names; do
      local plugin_dir="${PLUGINS_DIR}/${name}"

      if [[ ! -d "$plugin_dir" ]]; then
        warn "Plugin '${name}' is registered but directory is missing — skipping in loader."
        continue
      fi

      echo "# --- Plugin: ${name} ---"

      if [[ -d "${plugin_dir}/bin" ]]; then
        echo "export PATH=\"${plugin_dir}/bin:\$PATH\""
      fi

      if [[ -f "${plugin_dir}/lib/shell.sh" ]]; then
        echo "[[ -f \"${plugin_dir}/lib/shell.sh\" ]] && source \"${plugin_dir}/lib/shell.sh\""
      fi

      # Export env vars from manifest (safely quoted)
      local env_keys
      env_keys=$(jq -r '.env // {} | keys[]' "${plugin_dir}/plugin.json" 2>/dev/null || true)
      for key in $env_keys; do
        local val
        val=$(jq -r ".env[\"${key}\"]" "${plugin_dir}/plugin.json")
        echo "export ${key}=\"${val}\""
      done

      echo ""
    done
  } > "$tmp_loader"

  mv "$tmp_loader" "$LOADER_FILE"
  chmod 644 "$LOADER_FILE"
}

# ================================================================
# Resolve and install dependencies
# ================================================================
_check_deps() {
  local manifest_file="$1"
  local plugin_name
  plugin_name=$(jq -r '.name' "$manifest_file")

  local deps_count
  deps_count=$(jq '.dependencies // [] | length' "$manifest_file")
  [[ "$deps_count" -eq 0 ]] && return 0

  # Loop detection via colon-delimited chain in environment
  local dep_chain="${PLUGIN_DEP_CHAIN:-}"
  if [[ ":${dep_chain}:" == *":${plugin_name}:"* ]]; then
    warn "Dependency loop detected involving '${plugin_name}' — skipping."
    return 0
  fi
  export PLUGIN_DEP_CHAIN="${dep_chain:+${dep_chain}:}${plugin_name}"

  info "Checking dependencies for '${plugin_name}'..."

  local i=0
  while [[ $i -lt $deps_count ]]; do
    local dep
    dep=$(jq -c ".dependencies[$i]" "$manifest_file")

    local dep_name dep_url
    if [[ "$(echo "$dep" | jq -r 'type')" == "string" ]]; then
      dep_name=$(echo "$dep" | jq -r '.')
      dep_url=""
    else
      dep_name=$(echo "$dep" | jq -r '.name')
      dep_url=$(echo "$dep" | jq -r '.url // empty')
    fi

    sanitize_plugin_name "$dep_name" >/dev/null

    if [[ -d "${PLUGINS_DIR}/${dep_name}" ]]; then
      info "  Dependency '${dep_name}': already installed."
    elif [[ -n "$dep_url" ]]; then
      info "  Dependency '${dep_name}': not installed — auto-installing from ${dep_url}..."
      cmd_install "$dep_url"
    else
      warn "  Dependency '${dep_name}' is not installed and has no URL for auto-install."
      read -r -p "  Continue installing without '${dep_name}'? [y/N] " cont
      [[ "$cont" =~ ^[Yy]$ ]] || { info "Aborted."; exit 1; }
    fi

    i=$((i + 1))
  done
}

# ================================================================
# install
# ================================================================
cmd_install() {
  local url=""
  local pin_ref=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --pin) shift; pin_ref="${1:?--pin requires a ref argument}"; shift ;;
      -*) die "Unknown option: $1" ;;
      *) url="$1"; shift ;;
    esac
  done

  [[ -z "$url" ]] && die "Usage: plugin install <git-url> [--pin <ref>]"

  # Warn on non-HTTPS
  if [[ "$url" != https://* ]]; then
    warn "URL '${url}' is not HTTPS. Only install plugins from trusted sources."
    read -r -p "  Continue anyway? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
  fi

  require_plugins_dir
  ensure_registry_valid

  # Clone into a temp dir on the same filesystem to allow atomic mv
  local tmp_dir
  tmp_dir="$(mktemp -d "${PLUGINS_DIR}/.install_XXXXXX")"
  trap 'rm -rf "$tmp_dir"' EXIT

  info "Cloning ${url}..."
  if ! git clone --quiet "$url" "$tmp_dir" 2>&1 | sed 's/^/    /'; then
    die "git clone failed."
  fi

  if [[ -n "$pin_ref" ]]; then
    git -C "$tmp_dir" checkout --quiet "$pin_ref" 2>/dev/null \
      || die "Ref '${pin_ref}' not found in repository."
  fi

  validate_manifest "${tmp_dir}/plugin.json"

  local plugin_name version description author repo_url
  plugin_name=$(jq -r '.name' "${tmp_dir}/plugin.json")
  sanitize_plugin_name "$plugin_name" >/dev/null
  version=$(jq -r '.version' "${tmp_dir}/plugin.json")
  description=$(jq -r '.description' "${tmp_dir}/plugin.json")
  author=$(jq -r '.author // "unknown"' "${tmp_dir}/plugin.json")
  repo_url=$(jq -r '.repository // ""' "${tmp_dir}/plugin.json")

  # Show manifest and prompt
  echo ""
  echo "  ┌─ Plugin Manifest ─────────────────────────────────────"
  printf  "  │  Name:        %s\n" "$plugin_name"
  printf  "  │  Version:     %s\n" "$version"
  printf  "  │  Description: %s\n" "$description"
  printf  "  │  Author:      %s\n" "$author"
  [[ -n "$repo_url" ]] && printf "  │  Repository:  %s\n" "$repo_url"
  [[ -n "$pin_ref"  ]] && printf "  │  Pinned to:   %s\n" "$pin_ref"
  if [[ -f "${tmp_dir}/lib/shell.sh" ]]; then
    echo  "  │"
    echo  "  │  This plugin includes lib/shell.sh which will be"
    echo  "  │  sourced into every shell session."
    echo  "  │  Run 'plugin audit ${plugin_name}' to review it."
  fi
  echo  "  └───────────────────────────────────────────────────────"
  echo ""

  read -r -p "  Install plugin '${plugin_name}'? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

  local target_dir="${PLUGINS_DIR}/${plugin_name}"
  if [[ -d "$target_dir" ]]; then
    die "Plugin '${plugin_name}' is already installed. Run 'plugin remove ${plugin_name}' first."
  fi

  _check_deps "${tmp_dir}/plugin.json"

  # Move temp dir to final location (same filesystem — atomic rename)
  mv "$tmp_dir" "$target_dir"
  trap - EXIT

  # Register
  local installed_at
  installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  local new_registry
  new_registry=$(jq \
    --arg name "$plugin_name" \
    --arg url "$url" \
    --arg pin "$pin_ref" \
    --arg ts "$installed_at" \
    '.plugins[$name] = {url: $url, pin: (if $pin == "" then null else $pin end), installed_at: $ts}' \
    "$REGISTRY_FILE")
  echo "$new_registry" > "$REGISTRY_FILE"

  generate_loader

  echo ""
  info "Plugin '${plugin_name}' v${version} installed."
  info "Your current terminal will pick it up automatically."
}

# ================================================================
# remove
# ================================================================
cmd_remove() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin remove <name>"
  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir
  ensure_registry_valid

  local plugin_dir="${PLUGINS_DIR}/${name}"
  [[ -d "$plugin_dir" ]] || die "Plugin '${name}' is not installed."

  read -r -p "  Remove plugin '${name}'? This deletes ${plugin_dir}. [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

  rm -rf "$plugin_dir"

  local new_registry
  new_registry=$(jq --arg name "$name" 'del(.plugins[$name])' "$REGISTRY_FILE")
  echo "$new_registry" > "$REGISTRY_FILE"

  generate_loader
  info "Plugin '${name}' removed. Run 'reload-env' or open a new terminal to clear its commands."
}

# ================================================================
# update
# ================================================================
cmd_update() {
  local target_name=""
  local update_all=false
  local quiet=false

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all)   update_all=true; shift ;;
      --quiet) quiet=true; shift ;;
      -*)      die "Unknown option: $1" ;;
      *)       target_name="$1"; shift ;;
    esac
  done

  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    $quiet || info "No plugins installed."
    return 0
  fi

  if $update_all; then
    local any_updated=false
    for name in $plugin_names; do
      _update_one_plugin "$name" "$quiet" && any_updated=true || true
    done
    generate_loader
  elif [[ -n "$target_name" ]]; then
    sanitize_plugin_name "$target_name" >/dev/null
    _update_one_plugin "$target_name" "$quiet" || true
    generate_loader
  else
    die "Usage: plugin update <name> | --all [--quiet]"
  fi

  $quiet || info "Done. Open a new terminal or run 'reload-env' to apply updates."
}

_update_one_plugin() {
  local name="$1"
  local quiet="${2:-false}"
  local plugin_dir="${PLUGINS_DIR}/${name}"

  if [[ ! -d "$plugin_dir" ]]; then
    warn "Plugin '${name}' registered but directory missing — skipping."
    return 1
  fi

  local pin
  pin=$(jq -r --arg name "$name" '.plugins[$name].pin // empty' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -n "$pin" ]]; then
    # Check if pin is a tag (immutable) or branch
    if git -C "$plugin_dir" rev-parse "refs/tags/${pin}" >/dev/null 2>&1; then
      $quiet || info "Plugin '${name}': pinned to tag '${pin}' — skipping (tags are immutable)."
      return 0
    else
      # Pin is a branch
      $quiet || info "Updating '${name}' (branch '${pin}')..."
      if $quiet; then
        git -C "$plugin_dir" fetch --quiet origin >/dev/null 2>&1 || return 0
        git -C "$plugin_dir" checkout --quiet "$pin" >/dev/null 2>&1 || return 0
        git -C "$plugin_dir" merge --quiet "origin/${pin}" >/dev/null 2>&1 || return 0
      else
        git -C "$plugin_dir" fetch --quiet origin 2>&1 | sed 's/^/    /'
        git -C "$plugin_dir" checkout --quiet "$pin"
        git -C "$plugin_dir" merge --quiet "origin/${pin}" 2>&1 | sed 's/^/    /'
      fi
    fi
  else
    # Unpinned — pull current branch
    $quiet || info "Updating '${name}'..."
    if $quiet; then
      git -C "$plugin_dir" pull --quiet >/dev/null 2>&1 || return 0
    else
      git -C "$plugin_dir" pull --quiet 2>&1 | sed 's/^/    /'
    fi
  fi

  return 0
}

# ================================================================
# list
# ================================================================
cmd_list() {
  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    info "No plugins installed. Use 'plugin install <git-url>' to install one."
    return 0
  fi

  echo ""
  printf "  %-20s %-10s %-10s %-12s %s\n" "NAME" "VERSION" "PIN" "GIT HEAD" "DESCRIPTION"
  printf "  %-20s %-10s %-10s %-12s %s\n" "────────────────────" "─────────" "─────────" "───────────" "───────────"

  for name in $plugin_names; do
    local plugin_dir="${PLUGINS_DIR}/${name}"
    local version="(missing)" git_head="?" pin_val description deps_str
    pin_val=$(jq -r --arg n "$name" '.plugins[$n].pin // "-"' "$REGISTRY_FILE")

    if [[ -d "$plugin_dir" && -f "${plugin_dir}/plugin.json" ]]; then
      version=$(jq -r '.version // "?"' "${plugin_dir}/plugin.json")
      description=$(jq -r '.description // ""' "${plugin_dir}/plugin.json")
      deps_str=$(jq -r '[.dependencies[]? | if type=="string" then . else .name end] | join(", ")' \
        "${plugin_dir}/plugin.json" 2>/dev/null || echo "")
      git_head=$(git -C "$plugin_dir" rev-parse --short HEAD 2>/dev/null || echo "?")
    fi

    printf "  %-20s %-10s %-10s %-12s %s\n" \
      "$name" "$version" "$pin_val" "$git_head" "${description:-}"
    [[ -n "${deps_str:-}" ]] && \
      printf "  %-20s %-10s %-10s %-12s deps: %s\n" "" "" "" "" "$deps_str"
  done
  echo ""
}

# ================================================================
# docs
# ================================================================
cmd_docs() {
  local name="${1:-}"
  require_plugins_dir
  ensure_registry_valid

  if [[ -n "$name" ]]; then
    sanitize_plugin_name "$name" >/dev/null
    local readme="${PLUGINS_DIR}/${name}/docs/README.md"
    [[ -d "${PLUGINS_DIR}/${name}" ]] || die "Plugin '${name}' is not installed."
    if [[ ! -f "$readme" ]]; then
      die "No docs/README.md found for plugin '${name}'."
    fi
    _bat --style=plain --paging=always "$readme" 2>/dev/null || less "$readme"
  else
    local plugin_names
    plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)
    if [[ -z "$plugin_names" ]]; then
      info "No plugins installed."
      return 0
    fi
    echo ""
    for name in $plugin_names; do
      local desc has_docs="no"
      desc=$(jq -r '.description // "(no description)"' "${PLUGINS_DIR}/${name}/plugin.json" 2>/dev/null \
             || echo "(no manifest)")
      [[ -f "${PLUGINS_DIR}/${name}/docs/README.md" ]] && has_docs="yes"
      printf "  %-20s %-40s [docs: %s]\n" "$name" "$desc" "$has_docs"
    done
    echo ""
    info "Run 'plugin docs <name>' to view full documentation."
  fi
}

# ================================================================
# check-updates
# ================================================================
cmd_check_updates() {
  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    info "No plugins installed."
    return 0
  fi

  echo ""
  printf "  %-20s %-12s %-12s %s\n" "NAME" "LOCAL" "REMOTE" "STATUS"
  printf "  %-20s %-12s %-12s %s\n" "────────────────────" "───────────" "───────────" "──────"

  for name in $plugin_names; do
    local plugin_dir="${PLUGINS_DIR}/${name}"

    if [[ ! -d "$plugin_dir" ]]; then
      printf "  %-20s %-12s %-12s %s\n" "$name" "?" "?" "directory missing"
      continue
    fi

    git -C "$plugin_dir" fetch --quiet origin 2>/dev/null || {
      printf "  %-20s %-12s %-12s %s\n" "$name" "?" "?" "fetch failed (offline?)"
      continue
    }

    local local_head remote_ref status
    local_head=$(git -C "$plugin_dir" rev-parse --short HEAD 2>/dev/null || echo "?")
    remote_ref=$(git -C "$plugin_dir" rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>/dev/null || echo "")

    if [[ -n "$remote_ref" ]]; then
      local remote_head behind
      remote_head=$(git -C "$plugin_dir" rev-parse --short "$remote_ref" 2>/dev/null || echo "?")
      if [[ "$local_head" == "$remote_head" ]]; then
        status="up to date"
      else
        behind=$(git -C "$plugin_dir" rev-list --count HEAD.."$remote_ref" 2>/dev/null || echo "?")
        status="${behind} commit(s) behind — run 'plugin update ${name}'"
      fi
      printf "  %-20s %-12s %-12s %s\n" "$name" "$local_head" "$remote_head" "$status"
    else
      printf "  %-20s %-12s %-12s %s\n" "$name" "$local_head" "?" "no upstream configured"
    fi
  done
  echo ""
}

# ================================================================
# audit — show lib/shell.sh for review before sourcing
# ================================================================
cmd_audit() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin audit <name>"
  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir

  [[ -d "${PLUGINS_DIR}/${name}" ]] || die "Plugin '${name}' is not installed."

  local shell_sh="${PLUGINS_DIR}/${name}/lib/shell.sh"
  if [[ ! -f "$shell_sh" ]]; then
    info "Plugin '${name}' has no lib/shell.sh — nothing to audit."
    return 0
  fi

  echo ""
  echo "  ================================================================"
  echo "  Audit: ${shell_sh}"
  echo "  ================================================================"
  echo ""
  _bat --style=numbers,header --language=bash "$shell_sh" 2>/dev/null || cat "$shell_sh"
  echo ""
}

# ================================================================
# help
# ================================================================
cmd_help() {
  cat << 'HELP'

  plugin — Dev Container Plugin Manager  (v1)

  USAGE
    plugin <subcommand> [options]

  SUBCOMMANDS
    install <git-url> [--pin <ref>]
        Clone and install a plugin from a Git repository.
        Use --pin to lock to a specific tag or branch.
        Tag-pinned plugins are never auto-updated.

    remove <name>
        Uninstall a plugin and remove it from the loader.

    update <name> | --all [--quiet]
        Pull latest changes. Tag-pinned plugins are skipped.
        --all  updates every installed plugin.
        --quiet suppresses output (used by auto-update on start).

    list
        Show all installed plugins with versions and descriptions.

    docs [name]
        Show documentation for a plugin. Without a name, lists
        all installed plugins with a one-line summary.

    check-updates
        Fetch remote refs and report which plugins have updates.

    audit <name>
        Print lib/shell.sh so you can review it before sourcing.

    help
        Show this message.

  PLUGIN STRUCTURE
    Each plugin is a git repo with:
      plugin.json       manifest (name, version, description, dependencies, env)
      bin/              executables added to PATH
      lib/shell.sh      aliases/functions sourced at login
      docs/README.md    documentation

  SECURITY
    • Only install plugins from trusted HTTPS sources.
    • Review lib/shell.sh with: plugin audit <name>
    • Plugins run as the 'vscode' user — no root escalation.
    • Plugin names are restricted to [a-zA-Z0-9_-].

HELP
}

# ================================================================
# Main dispatcher
# ================================================================
main() {
  local subcmd="${1:-help}"
  shift || true

  case "$subcmd" in
    install)       cmd_install "$@" ;;
    remove)        cmd_remove "$@" ;;
    update)        cmd_update "$@" ;;
    list)          cmd_list "$@" ;;
    docs)          cmd_docs "$@" ;;
    check-updates) cmd_check_updates "$@" ;;
    audit)         cmd_audit "$@" ;;
    help|--help|-h) cmd_help ;;
    *) echo "  [plugin] Unknown subcommand: ${subcmd}" >&2; cmd_help; exit 1 ;;
  esac
}

main "$@"
