#!/usr/bin/env bash
# ================================================================
# plugin-manager.sh — Dev Container Plugin Manager
#
# Called via the plugin() shell function in .bashrc_devcontainer:
#   plugin() { bash /gantry/.devcontainer/scripts/plugin-manager.sh "$@"; ... }
#
# Never sourced — always run as a subprocess.
# ================================================================
set -euo pipefail

readonly PLUGINS_DIR="/gantry/.plugins"
readonly REGISTRY_FILE="${PLUGINS_DIR}/.registry.json"
readonly LOADER_FILE="${PLUGINS_DIR}/.loader.sh"
readonly MANAGER_VERSION="1"

# ================================================================
# Output helpers
# ================================================================
die()  { echo "  [plugin] ERROR: $*" >&2; exit 1; }
warn() { echo "  [plugin] WARNING: $*" >&2; }
info() { echo "  [plugin] $*"; }

# ================================================================
# bat/batcat/cat fallback for syntax-highlighted display
# ================================================================
_bat() {
  if command -v bat >/dev/null 2>&1; then
    bat "$@"
  elif command -v batcat >/dev/null 2>&1; then
    batcat "$@"
  else
    # Strip bat-specific flags and fall back to cat/less
    local args=()
    for arg in "$@"; do
      case "$arg" in
        --style=*|--paging=*|--language=*) ;;
        --paging) shift ;;
        *) args+=("$arg") ;;
      esac
    done
    cat "${args[@]}"
  fi
}

# ================================================================
# Guard: plugins directory must exist
# ================================================================
require_plugins_dir() {
  if [[ ! -d "$PLUGINS_DIR" ]]; then
    die "Plugin directory ${PLUGINS_DIR} does not exist. Run the devcontainer post-create script first."
  fi
  if [[ ! -f "$REGISTRY_FILE" ]]; then
    echo '{"plugins":{}}' > "$REGISTRY_FILE"
  fi
}

# ================================================================
# Guard: registry must be valid JSON
# ================================================================
ensure_registry_valid() {
  if ! jq empty "$REGISTRY_FILE" 2>/dev/null; then
    warn "Registry file is not valid JSON — resetting to empty registry."
    echo '{"plugins":{}}' > "$REGISTRY_FILE"
  fi
}

# ================================================================
# Validate plugin manifest has required fields
# ================================================================
validate_manifest() {
  local manifest_file="$1"
  if [[ ! -f "$manifest_file" ]]; then
    die "No plugin.json found in $(dirname "$manifest_file")"
  fi
  if ! jq empty "$manifest_file" 2>/dev/null; then
    die "plugin.json is not valid JSON in $(dirname "$manifest_file")"
  fi
  local required_fields=("name" "version" "description")
  for field in "${required_fields[@]}"; do
    local val
    val=$(jq -r ".${field} // empty" "$manifest_file")
    if [[ -z "$val" ]]; then
      die "plugin.json missing required field: ${field}"
    fi
  done
}

# ================================================================
# Reject plugin names with unsafe characters
# ================================================================
sanitize_plugin_name() {
  local name="$1"
  if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    die "Plugin name '${name}' contains invalid characters. Only alphanumeric, hyphens, and underscores are allowed."
  fi
  echo "$name"
}

# ================================================================
# Regenerate .loader.sh from the registry
# ================================================================
generate_loader() {
  require_plugins_dir
  ensure_registry_valid

  local tmp_loader
  tmp_loader="$(mktemp "${PLUGINS_DIR}/.loader_tmp_XXXXXX")"

  {
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by plugin manager — do not edit manually"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    local plugin_names
    plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

    for name in $plugin_names; do
      local plugin_dir="${PLUGINS_DIR}/${name}"

      if [[ ! -d "$plugin_dir" ]]; then
        warn "Plugin '${name}' is registered but directory is missing — skipping in loader."
        continue
      fi

      echo "# --- Plugin: ${name} ---"

      if [[ -d "${plugin_dir}/bin" ]]; then
        echo "export PATH=\"${plugin_dir}/bin:\$PATH\""
      fi

      if [[ -f "${plugin_dir}/lib/shell.sh" ]]; then
        echo "[[ -f \"${plugin_dir}/lib/shell.sh\" ]] && source \"${plugin_dir}/lib/shell.sh\""
      fi

      # Export env vars from manifest (safely quoted)
      local env_keys
      env_keys=$(jq -r '.env // {} | keys[]' "${plugin_dir}/plugin.json" 2>/dev/null || true)
      for key in $env_keys; do
        local val
        val=$(jq -r ".env[\"${key}\"]" "${plugin_dir}/plugin.json")
        echo "export ${key}=\"${val}\""
      done

      echo ""
    done
  } > "$tmp_loader"

  mv "$tmp_loader" "$LOADER_FILE"
  chmod 644 "$LOADER_FILE"
}

# ================================================================
# Resolve and install dependencies
# ================================================================
_check_deps() {
  local manifest_file="$1"
  local plugin_name
  plugin_name=$(jq -r '.name' "$manifest_file")

  local deps_count
  deps_count=$(jq '.dependencies // [] | length' "$manifest_file")
  [[ "$deps_count" -eq 0 ]] && return 0

  # Loop detection via colon-delimited chain in environment
  local dep_chain="${PLUGIN_DEP_CHAIN:-}"
  if [[ ":${dep_chain}:" == *":${plugin_name}:"* ]]; then
    warn "Dependency loop detected involving '${plugin_name}' — skipping."
    return 0
  fi
  export PLUGIN_DEP_CHAIN="${dep_chain:+${dep_chain}:}${plugin_name}"

  info "Checking dependencies for '${plugin_name}'..."

  local i=0
  while [[ $i -lt $deps_count ]]; do
    local dep
    dep=$(jq -c ".dependencies[$i]" "$manifest_file")

    local dep_name dep_url
    if [[ "$(echo "$dep" | jq -r 'type')" == "string" ]]; then
      dep_name=$(echo "$dep" | jq -r '.')
      dep_url=""
    else
      dep_name=$(echo "$dep" | jq -r '.name')
      dep_url=$(echo "$dep" | jq -r '.url // empty')
    fi

    sanitize_plugin_name "$dep_name" >/dev/null

    if [[ -d "${PLUGINS_DIR}/${dep_name}" ]]; then
      info "  Dependency '${dep_name}': already installed."
    elif [[ -n "$dep_url" ]]; then
      info "  Dependency '${dep_name}': not installed — auto-installing from ${dep_url}..."
      cmd_install "$dep_url"
    else
      warn "  Dependency '${dep_name}' is not installed and has no URL for auto-install."
      read -r -p "  Continue installing without '${dep_name}'? [y/N] " cont
      [[ "$cont" =~ ^[Yy]$ ]] || { info "Aborted."; exit 1; }
    fi

    i=$((i + 1))
  done
}

# ================================================================
# install
# ================================================================
cmd_install() {
  local url=""
  local pin_ref=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --pin) shift; pin_ref="${1:?--pin requires a ref argument}"; shift ;;
      -*) die "Unknown option: $1" ;;
      *) url="$1"; shift ;;
    esac
  done

  [[ -z "$url" ]] && die "Usage: plugin install <git-url> [--pin <ref>]"

  # Warn on non-HTTPS
  if [[ "$url" != https://* ]]; then
    warn "URL '${url}' is not HTTPS. Only install plugins from trusted sources."
    read -r -p "  Continue anyway? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
  fi

  require_plugins_dir
  ensure_registry_valid

  # Clone into a temp dir on the same filesystem to allow atomic mv
  local tmp_dir
  tmp_dir="$(mktemp -d "${PLUGINS_DIR}/.install_XXXXXX")"
  trap 'rm -rf "$tmp_dir"' EXIT

  info "Cloning ${url}..."
  if ! git clone --quiet "$url" "$tmp_dir" 2>&1 | sed 's/^/    /'; then
    die "git clone failed."
  fi

  if [[ -n "$pin_ref" ]]; then
    git -C "$tmp_dir" checkout --quiet "$pin_ref" 2>/dev/null \
      || die "Ref '${pin_ref}' not found in repository."
  fi

  validate_manifest "${tmp_dir}/plugin.json"

  local plugin_name version description author repo_url
  plugin_name=$(jq -r '.name' "${tmp_dir}/plugin.json")
  sanitize_plugin_name "$plugin_name" >/dev/null
  version=$(jq -r '.version' "${tmp_dir}/plugin.json")
  description=$(jq -r '.description' "${tmp_dir}/plugin.json")
  author=$(jq -r '.author // "unknown"' "${tmp_dir}/plugin.json")
  repo_url=$(jq -r '.repository // ""' "${tmp_dir}/plugin.json")

  # Show manifest and prompt
  echo ""
  echo "  ┌─ Plugin Manifest ─────────────────────────────────────"
  printf  "  │  Name:        %s\n" "$plugin_name"
  printf  "  │  Version:     %s\n" "$version"
  printf  "  │  Description: %s\n" "$description"
  printf  "  │  Author:      %s\n" "$author"
  [[ -n "$repo_url" ]] && printf "  │  Repository:  %s\n" "$repo_url"
  [[ -n "$pin_ref"  ]] && printf "  │  Pinned to:   %s\n" "$pin_ref"
  if [[ -f "${tmp_dir}/lib/shell.sh" ]]; then
    echo  "  │"
    echo  "  │  This plugin includes lib/shell.sh which will be"
    echo  "  │  sourced into every shell session."
    echo  "  │  Run 'plugin audit ${plugin_name}' to review it."
  fi
  echo  "  └───────────────────────────────────────────────────────"
  echo ""

  read -r -p "  Install plugin '${plugin_name}'? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

  local target_dir="${PLUGINS_DIR}/${plugin_name}"
  if [[ -d "$target_dir" ]]; then
    die "Plugin '${plugin_name}' is already installed. Run 'plugin remove ${plugin_name}' first."
  fi

  _check_deps "${tmp_dir}/plugin.json"

  # Move temp dir to final location (same filesystem — atomic rename)
  mv "$tmp_dir" "$target_dir"
  trap - EXIT

  # Register
  local installed_at
  installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  local new_registry
  new_registry=$(jq \
    --arg name "$plugin_name" \
    --arg url "$url" \
    --arg pin "$pin_ref" \
    --arg ts "$installed_at" \
    '.plugins[$name] = {url: $url, pin: (if $pin == "" then null else $pin end), installed_at: $ts}' \
    "$REGISTRY_FILE")
  echo "$new_registry" > "$REGISTRY_FILE"

  generate_loader

  echo ""
  info "Plugin '${plugin_name}' v${version} installed."
  info "Your current terminal will pick it up automatically."
}

# ================================================================
# remove
# ================================================================
cmd_remove() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin remove <name>"
  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir
  ensure_registry_valid

  local plugin_dir="${PLUGINS_DIR}/${name}"
  [[ -d "$plugin_dir" ]] || die "Plugin '${name}' is not installed."

  read -r -p "  Remove plugin '${name}'? This deletes ${plugin_dir}. [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

  rm -rf "$plugin_dir"

  local new_registry
  new_registry=$(jq --arg name "$name" 'del(.plugins[$name])' "$REGISTRY_FILE")
  echo "$new_registry" > "$REGISTRY_FILE"

  generate_loader
  info "Plugin '${name}' removed. Run 'reload-env' or open a new terminal to clear its commands."
}

# ================================================================
# update
# ================================================================
cmd_update() {
  local target_name=""
  local update_all=false
  local quiet=false

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all)   update_all=true; shift ;;
      --quiet) quiet=true; shift ;;
      -*)      die "Unknown option: $1" ;;
      *)       target_name="$1"; shift ;;
    esac
  done

  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    $quiet || info "No plugins installed."
    generate_loader
    return 0
  fi

  if $update_all; then
    local any_updated=false
    for name in $plugin_names; do
      _update_one_plugin "$name" "$quiet" && any_updated=true || true
    done
    generate_loader
  elif [[ -n "$target_name" ]]; then
    sanitize_plugin_name "$target_name" >/dev/null
    _update_one_plugin "$target_name" "$quiet" || true
    generate_loader
  else
    die "Usage: plugin update <name> | --all [--quiet]"
  fi

  $quiet || info "Done. Open a new terminal or run 'reload-env' to apply updates."
}

_update_one_plugin() {
  local name="$1"
  local quiet="${2:-false}"
  local plugin_dir="${PLUGINS_DIR}/${name}"

  if [[ ! -d "$plugin_dir" ]]; then
    warn "Plugin '${name}' registered but directory missing — skipping."
    return 1
  fi

  local pin
  pin=$(jq -r --arg name "$name" '.plugins[$name].pin // empty' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -n "$pin" ]]; then
    # Check if pin is a tag (immutable) or branch
    if git -C "$plugin_dir" rev-parse "refs/tags/${pin}" >/dev/null 2>&1; then
      $quiet || info "Plugin '${name}': pinned to tag '${pin}' — skipping (tags are immutable)."
      return 0
    else
      # Pin is a branch
      $quiet || info "Updating '${name}' (branch '${pin}')..."
      if $quiet; then
        git -C "$plugin_dir" fetch --quiet origin >/dev/null 2>&1 || return 0
        git -C "$plugin_dir" checkout --quiet "$pin" >/dev/null 2>&1 || return 0
        git -C "$plugin_dir" merge --quiet "origin/${pin}" >/dev/null 2>&1 || return 0
      else
        git -C "$plugin_dir" fetch --quiet origin 2>&1 | sed 's/^/    /'
        git -C "$plugin_dir" checkout --quiet "$pin"
        git -C "$plugin_dir" merge --quiet "origin/${pin}" 2>&1 | sed 's/^/    /'
      fi
    fi
  else
    # Unpinned — pull current branch
    $quiet || info "Updating '${name}'..."
    if $quiet; then
      git -C "$plugin_dir" pull --quiet >/dev/null 2>&1 || return 0
    else
      git -C "$plugin_dir" pull --quiet 2>&1 | sed 's/^/    /'
    fi
  fi

  return 0
}

# ================================================================
# list
# ================================================================
cmd_list() {
  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    info "No plugins installed. Use 'plugin install <git-url>' to install one."
    return 0
  fi

  echo ""
  printf "  %-20s %-10s %-10s %-12s %s\n" "NAME" "VERSION" "PIN" "GIT HEAD" "DESCRIPTION"
  printf "  %-20s %-10s %-10s %-12s %s\n" "────────────────────" "─────────" "─────────" "───────────" "───────────"

  for name in $plugin_names; do
    local plugin_dir="${PLUGINS_DIR}/${name}"
    local version="(missing)" git_head="?" pin_val description deps_str
    pin_val=$(jq -r --arg n "$name" '.plugins[$n].pin // "-"' "$REGISTRY_FILE")

    if [[ -d "$plugin_dir" && -f "${plugin_dir}/plugin.json" ]]; then
      version=$(jq -r '.version // "?"' "${plugin_dir}/plugin.json")
      description=$(jq -r '.description // ""' "${plugin_dir}/plugin.json")
      deps_str=$(jq -r '[.dependencies[]? | if type=="string" then . else .name end] | join(", ")' \
        "${plugin_dir}/plugin.json" 2>/dev/null || echo "")
      git_head=$(git -C "$plugin_dir" rev-parse --short HEAD 2>/dev/null || echo "?")
      local has_remote
      has_remote=$(git -C "$plugin_dir" remote get-url origin 2>/dev/null || echo "")
      [[ -z "$has_remote" ]] && description="${description} [local]"
    fi

    printf "  %-20s %-10s %-10s %-12s %s\n" \
      "$name" "$version" "$pin_val" "$git_head" "${description:-}"
    [[ -n "${deps_str:-}" ]] && \
      printf "  %-20s %-10s %-10s %-12s deps: %s\n" "" "" "" "" "$deps_str"
  done
  echo ""
}

# ================================================================
# docs
# ================================================================
cmd_docs() {
  local name="${1:-}"
  require_plugins_dir
  ensure_registry_valid

  if [[ -n "$name" ]]; then
    sanitize_plugin_name "$name" >/dev/null
    local readme="${PLUGINS_DIR}/${name}/docs/README.md"
    [[ -d "${PLUGINS_DIR}/${name}" ]] || die "Plugin '${name}' is not installed."
    if [[ ! -f "$readme" ]]; then
      die "No docs/README.md found for plugin '${name}'."
    fi
    _bat --style=plain --paging=always "$readme" 2>/dev/null || less "$readme"
  else
    local plugin_names
    plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)
    if [[ -z "$plugin_names" ]]; then
      info "No plugins installed."
      return 0
    fi
    echo ""
    for name in $plugin_names; do
      local desc has_docs="no"
      desc=$(jq -r '.description // "(no description)"' "${PLUGINS_DIR}/${name}/plugin.json" 2>/dev/null \
             || echo "(no manifest)")
      [[ -f "${PLUGINS_DIR}/${name}/docs/README.md" ]] && has_docs="yes"
      printf "  %-20s %-40s [docs: %s]\n" "$name" "$desc" "$has_docs"
    done
    echo ""
    info "Run 'plugin docs <name>' to view full documentation."
  fi
}

# ================================================================
# check-updates
# ================================================================
cmd_check_updates() {
  require_plugins_dir
  ensure_registry_valid

  local plugin_names
  plugin_names=$(jq -r '.plugins | keys[]' "$REGISTRY_FILE" 2>/dev/null || true)

  if [[ -z "$plugin_names" ]]; then
    info "No plugins installed."
    return 0
  fi

  echo ""
  printf "  %-20s %-12s %-12s %s\n" "NAME" "LOCAL" "REMOTE" "STATUS"
  printf "  %-20s %-12s %-12s %s\n" "────────────────────" "───────────" "───────────" "──────"

  for name in $plugin_names; do
    local plugin_dir="${PLUGINS_DIR}/${name}"

    if [[ ! -d "$plugin_dir" ]]; then
      printf "  %-20s %-12s %-12s %s\n" "$name" "?" "?" "directory missing"
      continue
    fi

    git -C "$plugin_dir" fetch --quiet origin 2>/dev/null || {
      printf "  %-20s %-12s %-12s %s\n" "$name" "?" "?" "fetch failed (offline?)"
      continue
    }

    local local_head remote_ref status
    local_head=$(git -C "$plugin_dir" rev-parse --short HEAD 2>/dev/null || echo "?")
    remote_ref=$(git -C "$plugin_dir" rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>/dev/null || echo "")

    if [[ -n "$remote_ref" ]]; then
      local remote_head behind
      remote_head=$(git -C "$plugin_dir" rev-parse --short "$remote_ref" 2>/dev/null || echo "?")
      if [[ "$local_head" == "$remote_head" ]]; then
        status="up to date"
      else
        behind=$(git -C "$plugin_dir" rev-list --count HEAD.."$remote_ref" 2>/dev/null || echo "?")
        status="${behind} commit(s) behind — run 'plugin update ${name}'"
      fi
      printf "  %-20s %-12s %-12s %s\n" "$name" "$local_head" "$remote_head" "$status"
    else
      printf "  %-20s %-12s %-12s %s\n" "$name" "$local_head" "?" "no upstream configured"
    fi
  done
  echo ""
}

# ================================================================
# audit — show lib/shell.sh for review before sourcing
# ================================================================
cmd_audit() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin audit <name>"
  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir

  [[ -d "${PLUGINS_DIR}/${name}" ]] || die "Plugin '${name}' is not installed."

  local shell_sh="${PLUGINS_DIR}/${name}/lib/shell.sh"
  if [[ ! -f "$shell_sh" ]]; then
    info "Plugin '${name}' has no lib/shell.sh — nothing to audit."
    return 0
  fi

  echo ""
  echo "  ================================================================"
  echo "  Audit: ${shell_sh}"
  echo "  ================================================================"
  echo ""
  _bat --style=numbers,header --language=bash "$shell_sh" 2>/dev/null || cat "$shell_sh"
  echo ""
}

# ================================================================
# new — scaffold a local plugin
# ================================================================
cmd_new() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin new <name> [--description <desc>] [--author <author>] [--version <ver>]"
  shift || true

  local opt_description="" opt_author="" opt_version="1.0.0"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --description) shift; opt_description="${1:?--description requires a value}"; shift ;;
      --author)      shift; opt_author="${1:?--author requires a value}"; shift ;;
      --version)     shift; opt_version="${1:?--version requires a value}"; shift ;;
      *) die "Unknown option: $1" ;;
    esac
  done

  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir
  ensure_registry_valid

  local plugin_dir="${PLUGINS_DIR}/${name}"
  [[ -d "$plugin_dir" ]] && die "Plugin '${name}' already exists at ${plugin_dir}."

  # Collect info interactively for any fields not provided as flags
  if [[ -z "$opt_description" ]]; then
    read -r -p "  Description: " opt_description
    opt_description="${opt_description:-A dev container plugin}"
  fi
  if [[ -z "$opt_author" ]]; then
    local default_author
    default_author=$(git config --global user.name 2>/dev/null \
                     || gh api user --jq .name 2>/dev/null \
                     || echo "")
    read -r -p "  Author [${default_author:-your name}]: " input_author
    opt_author="${input_author:-${default_author:-devcontainer}}"
  fi

  # Create directory structure
  mkdir -p "${plugin_dir}/bin" "${plugin_dir}/lib" "${plugin_dir}/docs"

  # plugin.json
  jq -n \
    --arg name        "$name" \
    --arg version     "$opt_version" \
    --arg description "$opt_description" \
    --arg author      "$opt_author" \
    '{name: $name, version: $version, description: $description,
      author: $author, repository: "", dependencies: [], env: {}}' \
    > "${plugin_dir}/plugin.json"

  # bin/<name> — main executable
  cat > "${plugin_dir}/bin/${name}" << BINEOF
#!/usr/bin/env bash
# ${name} — main command
# TODO: add your implementation here
echo "Hello from the ${name} plugin!"
BINEOF
  chmod +x "${plugin_dir}/bin/${name}"

  # lib/shell.sh — sourced at login (use single-quote delimiter to avoid expansion)
  cat > "${plugin_dir}/lib/shell.sh" << 'SHELLEOF_SENTINEL'
# PLUGIN_NAME plugin — shell integration
# Aliases and functions sourced into every shell session.
# Uncomment or add your own below.

# alias PLUGIN_NAME-hello='echo "Hello from PLUGIN_NAME!"'

# PLUGIN_NAME-status() {
#   echo "PLUGIN_NAME plugin is active"
# }
SHELLEOF_SENTINEL
  # Replace the PLUGIN_NAME sentinel with the actual name
  sed -i "s/PLUGIN_NAME/${name}/g" "${plugin_dir}/lib/shell.sh"

  # docs/README.md
  cat > "${plugin_dir}/docs/README.md" << DOCSEOF
# ${name}

${opt_description}

## Installation

\`\`\`bash
plugin install <repository-url>
\`\`\`

## Commands

| Command | Description |
|---------|-------------|
| \`${name}\` | Main command — describe what it does |

## Shell Aliases & Functions

*(document the aliases/functions in lib/shell.sh here)*

## Examples

\`\`\`bash
${name}
\`\`\`
DOCSEOF

  # .gitignore
  printf '*.log\n.DS_Store\n' > "${plugin_dir}/.gitignore"

  # Initialize git repository
  git -C "$plugin_dir" init --quiet

  # Ensure local git user config exists for the initial commit.
  # The devcontainer may not have a global ~/.gitconfig from the host.
  if ! git -C "$plugin_dir" config user.name >/dev/null 2>&1; then
    local git_user git_email
    git_user=$(git config --global user.name 2>/dev/null \
               || gh api user --jq .login 2>/dev/null \
               || echo "devcontainer")
    git_email=$(git config --global user.email 2>/dev/null \
                || echo "${git_user}@localhost")
    git -C "$plugin_dir" config user.name  "$git_user"
    git -C "$plugin_dir" config user.email "$git_email"
  fi

  git -C "$plugin_dir" add .
  git -C "$plugin_dir" commit --quiet -m "chore: initial plugin scaffold"

  # Register as local plugin (no remote URL yet)
  local installed_at
  installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  local new_registry
  new_registry=$(jq \
    --arg name "$name" \
    --arg ts   "$installed_at" \
    '.plugins[$name] = {url: null, pin: null, installed_at: $ts, local: true}' \
    "$REGISTRY_FILE")
  echo "$new_registry" > "$REGISTRY_FILE"

  generate_loader

  echo ""
  info "Plugin '${name}' created at ${plugin_dir}"
  echo ""
  echo "  Next steps:"
  printf "    1. Edit %s/plugin.json\n"    "$plugin_dir"
  printf "    2. Edit %s/bin/%s\n"         "$plugin_dir" "$name"
  printf "    3. Edit %s/lib/shell.sh\n"   "$plugin_dir"
  printf "    4. Edit %s/docs/README.md\n" "$plugin_dir"
  echo   "    5. Run 'plugin publish ${name}' when ready to share"
  echo ""
  info "Your current terminal will pick up the new plugin automatically."
}

# ================================================================
# publish — push a local plugin to GitHub
# ================================================================
cmd_publish() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: plugin publish <name> [--public|--private] [--org <org>]"
  shift || true

  local visibility="public" org=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --public)  visibility="public";  shift ;;
      --private) visibility="private"; shift ;;
      --org)     shift; org="${1:?--org requires an organization name}"; shift ;;
      *) die "Unknown option: $1" ;;
    esac
  done

  sanitize_plugin_name "$name" >/dev/null
  require_plugins_dir
  ensure_registry_valid

  local plugin_dir="${PLUGINS_DIR}/${name}"
  [[ -d "$plugin_dir" ]]        || die "Plugin '${name}' is not installed."
  [[ -d "${plugin_dir}/.git" ]] || die "Plugin '${name}' is not a git repository. Run 'plugin new ${name}' to initialize one."

  command -v gh &>/dev/null   || die "'gh' (GitHub CLI) is not installed."
  gh auth status &>/dev/null  || die "Not authenticated with GitHub. Run 'gh auth login' first."

  # Offer to commit any uncommitted changes before pushing
  if [[ -n "$(git -C "$plugin_dir" status --porcelain 2>/dev/null)" ]]; then
    warn "Plugin '${name}' has uncommitted changes."
    read -r -p "  Commit all changes now before publishing? [Y/n] " do_commit
    if [[ ! "$do_commit" =~ ^[Nn]$ ]]; then
      git -C "$plugin_dir" add .
      read -r -p "  Commit message [chore: update plugin]: " commit_msg
      git -C "$plugin_dir" commit --quiet -m "${commit_msg:-chore: update plugin}"
    fi
  fi

  local existing_remote
  existing_remote=$(git -C "$plugin_dir" remote get-url origin 2>/dev/null || echo "")

  if [[ -n "$existing_remote" ]]; then
    # Remote already configured — just push
    info "Remote 'origin': ${existing_remote}"
    read -r -p "  Push to '${existing_remote}'? [Y/n] " do_push
    [[ "$do_push" =~ ^[Nn]$ ]] && { info "Aborted."; exit 0; }

    git -C "$plugin_dir" push origin 2>&1 | sed 's/^/    /'

    # Back-fill registry URL if this was a local plugin (url was null)
    local current_url
    current_url=$(jq -r --arg n "$name" '.plugins[$n].url // empty' "$REGISTRY_FILE")
    if [[ -z "$current_url" ]]; then
      local new_registry
      new_registry=$(jq \
        --arg name "$name" --arg url "$existing_remote" \
        '.plugins[$name].url = $url | .plugins[$name].local = false' \
        "$REGISTRY_FILE")
      echo "$new_registry" > "$REGISTRY_FILE"
    fi

    info "Plugin '${name}' pushed to ${existing_remote}."

  else
    # No remote — create new GitHub repo and push
    local repo_name="${org:+${org}/}${name}"

    info "Creating GitHub repository '${repo_name}' (${visibility})..."

    gh repo create "$repo_name" \
      --source="$plugin_dir" \
      --remote=origin \
      "--${visibility}" \
      --push 2>&1 | sed 's/^/    /'

    local repo_url
    repo_url=$(git -C "$plugin_dir" remote get-url origin 2>/dev/null || echo "")

    # Update plugin.json repository field and commit the change
    if [[ -n "$repo_url" ]]; then
      local updated_json
      updated_json=$(jq --arg url "$repo_url" '.repository = $url' "${plugin_dir}/plugin.json")
      echo "$updated_json" > "${plugin_dir}/plugin.json"
      git -C "$plugin_dir" add plugin.json
      git -C "$plugin_dir" commit --quiet -m "chore: add repository url to manifest" 2>/dev/null || true
      git -C "$plugin_dir" push --quiet origin 2>/dev/null || true
    fi

    # Update registry
    local new_registry
    new_registry=$(jq \
      --arg name "$name" --arg url "${repo_url:-}" \
      '.plugins[$name].url = $url | .plugins[$name].local = false' \
      "$REGISTRY_FILE")
    echo "$new_registry" > "$REGISTRY_FILE"

    echo ""
    info "Plugin '${name}' published!"
    [[ -n "$repo_url" ]] && info "Repository: ${repo_url}"
    echo ""
    echo "  Others can install it with:"
    echo "    plugin install ${repo_url:-<repository-url>}"
  fi
}

# ================================================================
# help
# ================================================================
cmd_help() {
  cat << 'HELP'

  plugin — Dev Container Plugin Manager  (v1)

  USAGE
    plugin <subcommand> [options]

  SUBCOMMANDS
    install <git-url> [--pin <ref>]
        Clone and install a plugin from a Git repository.
        Use --pin to lock to a specific tag or branch.
        Tag-pinned plugins are never auto-updated.

    remove <name>
        Uninstall a plugin and remove it from the loader.

    update <name> | --all [--quiet]
        Pull latest changes. Tag-pinned plugins are skipped.
        --all  updates every installed plugin.
        --quiet suppresses output (used by auto-update on start).

    list
        Show all installed plugins with versions and descriptions.
        Plugins with no remote origin are marked [local].

    docs [name]
        Show documentation for a plugin. Without a name, lists
        all installed plugins with a one-line summary.

    check-updates
        Fetch remote refs and report which plugins have updates.

    audit <name>
        Print lib/shell.sh so you can review it before sourcing.

    new <name> [--description <desc>] [--author <author>] [--version <ver>]
        Scaffold a new plugin in .plugins/<name>/ with full directory
        structure, starter files, and an initial git commit.
        Prompts interactively for any fields not supplied as flags.

    publish <name> [--public|--private] [--org <org>]
        Push a locally developed plugin to GitHub.
        Creates a new GitHub repo if no remote is configured.
        Updates plugin.json with the repository URL after publishing.
        Requires 'gh auth login' on the host (or GH_TOKEN env var).

    generate-loader
        Regenerate .plugins/.loader.sh from the registry.
        Run this if plugin commands are missing after a rebuild.

    help
        Show this message.

  PLUGIN STRUCTURE
    Each plugin is a git repo with:
      plugin.json       manifest (name, version, description, dependencies, env)
      bin/              executables added to PATH
      lib/shell.sh      aliases/functions sourced at login
      docs/README.md    documentation

  SECURITY
    • Only install plugins from trusted HTTPS sources.
    • Review lib/shell.sh with: plugin audit <name>
    • Plugins run as the 'vscode' user — no root escalation.
    • Plugin names are restricted to [a-zA-Z0-9_-].

HELP
}

# ================================================================
# Main dispatcher
# ================================================================
main() {
  local subcmd="${1:-help}"
  shift || true

  case "$subcmd" in
    install)         cmd_install "$@" ;;
    remove)          cmd_remove "$@" ;;
    update)          cmd_update "$@" ;;
    list)            cmd_list "$@" ;;
    docs)            cmd_docs "$@" ;;
    check-updates)   cmd_check_updates "$@" ;;
    audit)           cmd_audit "$@" ;;
    new)             cmd_new "$@" ;;
    publish)         cmd_publish "$@" ;;
    generate-loader) require_plugins_dir; ensure_registry_valid; generate_loader ;;
    help|--help|-h)  cmd_help ;;
    *) echo "  [plugin] Unknown subcommand: ${subcmd}" >&2; cmd_help; exit 1 ;;
  esac
}

main "$@"
